<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Js Examples : - </title>
    <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet">
    <style>
        *, *:before,*:after{
            font-family: 'Source Code Pro', monospace;
            font-size: 14px;
        }
        #dispalyError {
            padding: 7px;
            color: red;
            font-size: 18px;
            font-weight: bold;
        }
    </style>
</head>

<body>

    <div id="dispalyError">
    </div>

    <h1>Error Objects </h1>
    <dl>
        <dt>1.Error</dt>
        <dd>
            <p>
                The “Error” type is used to represent generic exceptions. This type of exception is most often used for implementing user
                defined exceptions. The topic of creating user defined exceptions will be revisited later in this article.
                “Error” objects are instantiated by calling their constructor as shown in the following example. var error
            </p>
            <p>
                “Error” objects contain two properties, “name” and “message”. The “name” property specifies the type of exception (in this
                case “Error”). The “message” property provides a more detailed description of the exception. The “message”
                gets its value from the string passed to the exception’s constructor. The remaining exception types represent
                more specific types of errors, but they are all used in the same fashion as the generic “Error” type.
            </p>
            <code>
                <pre>
                    var error = new Error("error message");
                </pre>
            </code>
        </dd>

        <dt>2.RangeError</dt>
        <dd>
            <p>
                “RangeError” exceptions are generated by numbers that fall outside of a specified range. For example, JavaScript numbers
                have a toFixed() method which takes a “digits” argument representing the number of digits to appear after
                a decimal point. This argument is expected to be between 0 and 20 (although some browsers support a wider
                range). If the value of “digits” is outside of this range, then a “RangeError” is thrown. This scenario is
                shown in the following example.
            </p>
            <code>
                <pre>
                    var pi = 3.14159;
                    pi.toFixed(100000); // RangeError
                </pre>
            </code>
        </dd>

        <dt>3.ReferenceError</dt>
        <dd>
            <p>
                A “ReferenceError” exception is thrown when a non-existent variable is accessed. These exceptions commonly occur when an
                existing variable name is misspelled. In the example below, a “ReferenceError” occurs when “bar” is accessed.
                Note that this example assumes that “bar” does not exist in any active scope when the increment operation
                is attempted.
            </p>
            <code>
                <pre>
                function foo() {
                     bar++;  // ReferenceError
                }
                </pre>
            </code>
        </dd>


        <dt>4.SyntaxError</dt>
        <dd>
            <p>
                A “SyntaxError” is thrown when the rules of the JavaScript language are broken. Developers who are familiar with languages
                such as C and Java are used to encountering syntax errors during the compilation process. However, because
                JavaScript is an interpreted language, syntax errors are not identified until the code is executed. Syntax
                errors are unique as they are the only type of exception that cannot be recovered from. The following example
                generates a syntax error because the “if” statement is missing a closing curly brace.
            </p>
            <code>
                <pre>
                    if (foo) {  // SyntaxError
                    // the closing curly brace is missing
                </pre>
            </code>
        </dd>


        <dt>5.TypeError</dt>
        <dd>
            <p>
                A “TypeError” exception occurs when a value is not of the expected type. Attempting to call a non-existent object method
                is a common cause of this type of exception. The following example creates an empty object named “foo” and
                then attempts to invoke its bar() method. Since bar() is not defined, a “TypeError” is thrown upon the attempted
                invocation.
            </p>
            <code>
                <pre>
                var foo = {};
                foo.bar(); // TypeError
                </pre>
            </code>
        </dd>

        <dt>6.URIError</dt>
        <dd>
            <p>
                A “URIError” exception is thrown by methods such as encodeURI() and decodeURI() when they encounter a malformed URI. The
                following example generates a “URIError” while attempting to decode the string “%”. The “%” character represents
                the beginning of a URI escape sequence. Since nothing follows the “%” in this example, the string is an invalid
                escape sequence, and therefore a malformed URI component.
            </p>
            <code>
                <pre>
                    decodeURIComponent("%"); // URIError
                </pre>
            </code>
        </dd>

        <dt>7.EvalError</dt>
        <dd>
            <p>
                “EvalError” exceptions are thrown when the eval() function is used improperly. These exceptions are not used in the most
                recent version of the EcmaScript standard. However, they are still supported in order to maintain backwards
                compatibility with older versions of the standard.
            </p>
        </dd>

    </dl>

    <script type="text/javascript">
        try {
            satyaspb();
        } catch (exception) {

            var msg;

            if (exception instanceof TypeError) {
                msg = "TypeError";
            } else if (exception instanceof ReferenceError) {
                msg = "ReferenceError";
            } else if (exception instanceof RangeError) {
                msg = "RangeError";
            } else if (exception instanceof SyntaxError) {
                msg = "SyntaxError";
            } else if (exception instanceof URIError) {
                msg = "URIError";
            } else if (exception instanceof EvalError) {
                msg = "EvalError";
            } else {
                msg = new Error("Thisis custom error message");
            }

            // const Type = {
            //     Error: TypeError,
            //     Reference: ReferenceError,
            //     Range: RangeError,
            //     Syntax: SyntaxError,
            //     URI: URIError,
            //     Eval: EvalError
            // }

            // switch (exception) {
            //     case Type.Error:
            //         msg = "This is TypeError"
            //     case Type.Reference:    
            //         msg = "This is Referecene Error"
            //     case Type.Range:
            //         msg = "This is Range Error"
            //     case Type.Syntax:
            //         msg = "This is Syntax Error"
            //     case Type.URI:
            //         msg = "This is URIError Error"
            //     case Type.Eval:
            //         msg = "This is Eval Error"
            //     // default:
            //     //     msg = new Error("Hi This is Default Message")
            // }

            document.getElementById("dispalyError").innerHTML = msg;
        }
    </script>

</body>

</html>